### ISSUE TITLE
ghttp可以增加 关闭默认日志选项

### ISSUE THREAD

**Issue by CCpro10** [giant-stone/go#13]
在某些场景，有时候发送请求不需要日志，打印日志反而会使日志数据过多。
增加选项关闭所有日志？
或者增加选项，成功时不输出日志？

**Comment by tonytony2020** [comment]
不支持按模块设置日志。


只支持设置全局，如 设置 为 warn 级别

```
	glogging.Init([]string{"stderr"}, "warn")
```


这个设计遵循

> 系统设计通用原则
> [KISS](https://en.wikipedia.org/wiki/KISS_principle)
> [Don't Make Me Think](https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think)
> 如无必要，不要打扰用户
> 反例：有事无事，都打印大量日志
> 打印日志要么不打，要打就尽可能带上[5W+1H](https://en.wikipedia.org/wiki/Five_Ws)上下文信息以便后续跟踪

https://github.com/ggt1024/styleguide
